Disable checking api version in example/scikit-learn
neulab/explainaboard_client pull request #64
Opened 2022-12-09 19:09 UTC by OscarWang114

A data scientist has reported facing an API version mismatch exception. Because our prod server uses API client version 0.2.17 and the CLI uses 0.2.23, we need to disable version checking. 

Alternatively, we can also set `explainaboard-api-client==0.2.17` in requirements.txt. I don't really have a preference between these two.

In the long run, I think a better way is to have two branches `dev` and `main`. The former's version will align with our dev server and the latter with our prod server.

2022-12-15 21:19 UTC, noelchen90 approved these changes

2022-12-19 22:47 UTC, neubig commented
If you don't mind, I'd like to avoid doing this for now. We've upgraded to the most recent client for the web interface and changes will probably be less frequent for a bit. We can open an issue with respect to having separate "dev" and "prod" branches though.

2022-12-19 22:48 UTC, neubig requested changes
If you don't mind, I'd like to avoid doing this for now as it's a bit dangerous, and changes should be a bit less frequent for the time being.

Maybe we can create an issue about having separate dev and prod branches in the future?

2022-12-20 17:11 UTC, lyuyangh commented
btw, I think this is no longer an issue because we have deployed the latest version.

2022-12-22 04:31 UTC, OscarWang114 commented
@neubig Thanks, I agree and will create an issue. Thanks @lyuyangh for the reminder too!

2022-12-22 04:31 UTC, closed without merging